markdown: CommonMarkGhPages

title: Garrett Tetrault
author: Garrett Tetrault
email: "grtetrault (at) pm (dot) me"
github_username: grtetrault
linkedin_username: garretttetrault

url: ""
baseurl: ""

blog: /blog
permalink: /blog/:slug
