markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "FOOTNOTES"]
  extensions: ["table"]

title: Garrett Tetrault
author: Garrett Tetrault
email: "grtetrault (at) pm (dot) me"
github_username: grtetrault
linkedin_username: garretttetrault

url: "https://grtetrault.github.io"
baseurl: ""

blog: /blog
permalink: /blog/:slug
